---


- name: Ensure user exists and belongs to supergroup
  ansible.builtin.user:
    name: "{{ item.name }}"
    append: yes
    state: present
  with_items: "{{ users }}"


- name: Configure a ssh auth-key for user
  ansible.builtin.authorized_key:
    user: "{{ item.name }}"
    key:  "{{ item.ssh  }}"
    state: present
  loop: "{{ users }}"
